type TradingState = {
  [key: string]: "running" | "paused" | "stopped";
};

const startTradingState = (key: string, tradingState: TradingState) => {
  return tradingState[key] === "stopped" || tradingState[key] === undefined;
};
const pauseTradingState = (key: string, tradingState: TradingState) => {
  return tradingState[key] === "running" || tradingState[key] === undefined;
};
const resumeTradingState = (key: string, tradingState: TradingState) => {
  return tradingState[key] === "paused" || tradingState[key] === undefined;
};
const stopTradingState = (key: string, tradingState: TradingState) => {
  return tradingState[key] === "running" || tradingState[key] === "paused";
};

const SampleData = [
  {
    executionParams: {
      product: "NRML",
      strategyTag: "tag_8e65a34d1c45",
      legsExecution: "Parallel",
      portfolioExecutionMode: "startTime",
      entryOrderType: "LIMIT",
      runOnDays: ["Thursday"],
      startTime: "",
      endTime: "",
      squareoffTime: "",
    },
    timestamp: "2025-11-27T13:06:07.525272",
    targetSettings: {
      targetType: "CombinedProfit",
      targetValue: 0.0,
    },
    legs: {
      LEG_001: {
        markedAsComplete: false,
        id: 1764223999953,
        legId: "LEG_001",
        strategyId: "STRATEGY_996751",
        strategyName: "NIFTY_NEW",
        symbol: "NIFTY",
        expiry: 0,
        priceType: "BIDASK",
        depthIndex: 1,
        orderType: "LIMIT",
        action: "SELL",
        optionType: "CE",
        lots: 1,
        strike: "ATM",
        target: "POINTS",
        targetValue: 1.0,
        stoploss: "POINTS",
        stoplossValue: 1.0,
        startTime: "",
        waitAndTrade: 0.0,
        waitAndTradeLogic: "NONE",
        dynamicHedge: true,
        onSquareOffAction: "NONE",
        onTargetActionConfig: {
          actionType: "NONE",
          actionCount: 1,
          orderAtBroker: false,
          slOrderAdjust: {
            minPoints: 0.0,
            maxPercentage: 0.0,
          },
        },
        onStoplossActionConfig: {
          actionType: "NONE",
          actionCount: 1,
          orderAtBroker: false,
          slOrderAdjust: {
            minPoints: 0.0,
            maxPercentage: 0.0,
          },
        },
        onSquareOffActionConfig: {
          actionType: "NONE",
          actionCount: 1,
          orderAtBroker: false,
          slOrderAdjust: {
            minPoints: 0.0,
            maxPercentage: 0.0,
          },
        },
        premiumBasedStrike: true,
        premiumBasedStrikeConfig: {
          strikeType: "NearestPremium",
          maxDepth: 25,
          searchSide: "OTM",
          value: 20.0,
          condition: "Greaterthanequal",
          between: 0.0,
          and_value: 0.0,
        },
        hedgeSelectedStrike: null,
        selectedStrike: null,
        reEnterCount: 0,
        reEnterLogic: "NONE",
        initialLegPrice: 0,
      },
      LEG_002: {
        markedAsComplete: false,
        id: 1764224033614,
        legId: "LEG_002",
        strategyId: "STRATEGY_996751",
        strategyName: "NIFTY_NEW",
        symbol: "NIFTY",
        expiry: 0,
        priceType: "BIDASK",
        depthIndex: 1,
        orderType: "LIMIT",
        action: "SELL",
        optionType: "CE",
        lots: 1,
        strike: "ATM",
        target: "POINTS",
        targetValue: 1.0,
        stoploss: "POINTS",
        stoplossValue: 1.0,
        startTime: "",
        waitAndTrade: 2.0,
        waitAndTradeLogic: "POINTS",
        dynamicHedge: true,
        onSquareOffAction: "NONE",
        onTargetActionConfig: {
          actionType: "NONE",
          actionCount: 1,
          orderAtBroker: false,
          slOrderAdjust: {
            minPoints: 0.0,
            maxPercentage: 0.0,
          },
        },
        onStoplossActionConfig: {
          actionType: "NONE",
          actionCount: 1,
          orderAtBroker: false,
          slOrderAdjust: {
            minPoints: 0.0,
            maxPercentage: 0.0,
          },
        },
        onSquareOffActionConfig: {
          actionType: "NONE",
          actionCount: 1,
          orderAtBroker: false,
          slOrderAdjust: {
            minPoints: 0.0,
            maxPercentage: 0.0,
          },
        },
        premiumBasedStrike: true,
        premiumBasedStrikeConfig: {
          strikeType: "NearestPremium",
          maxDepth: 25,
          searchSide: "OTM",
          value: 20.0,
          condition: "Greaterthanequal",
          between: 0.0,
          and_value: 0.0,
        },
        hedgeSelectedStrike: null,
        selectedStrike: null,
        reEnterCount: 0,
        reEnterLogic: "NONE",
        initialLegPrice: 0,
      },
      LEG_003: {
        markedAsComplete: false,
        id: 1764224042630,
        legId: "LEG_003",
        strategyId: "STRATEGY_996751",
        strategyName: "NIFTY_NEW",
        symbol: "NIFTY",
        expiry: 0,
        priceType: "BIDASK",
        depthIndex: 1,
        orderType: "LIMIT",
        action: "SELL",
        optionType: "PE",
        lots: 1,
        strike: "ATM",
        target: "POINTS",
        targetValue: 1.0,
        stoploss: "POINTS",
        stoplossValue: 1.0,
        startTime: "",
        waitAndTrade: 2.0,
        waitAndTradeLogic: "POINTS",
        dynamicHedge: true,
        onSquareOffAction: "NONE",
        onTargetActionConfig: {
          actionType: "NONE",
          actionCount: 1,
          orderAtBroker: false,
          slOrderAdjust: {
            minPoints: 0.0,
            maxPercentage: 0.0,
          },
        },
        onStoplossActionConfig: {
          actionType: "NONE",
          actionCount: 1,
          orderAtBroker: false,
          slOrderAdjust: {
            minPoints: 0.0,
            maxPercentage: 0.0,
          },
        },
        onSquareOffActionConfig: {
          actionType: "NONE",
          actionCount: 1,
          orderAtBroker: false,
          slOrderAdjust: {
            minPoints: 0.0,
            maxPercentage: 0.0,
          },
        },
        premiumBasedStrike: true,
        premiumBasedStrikeConfig: {
          strikeType: "NearestPremium",
          maxDepth: 25,
          searchSide: "OTM",
          value: 20.0,
          condition: "Greaterthanequal",
          between: 0.0,
          and_value: 0.0,
        },
        hedgeSelectedStrike: null,
        selectedStrike: null,
        reEnterCount: 0,
        reEnterLogic: "NONE",
        initialLegPrice: 0,
      },
      LEG_004: {
        markedAsComplete: false,
        id: 1764224048928,
        legId: "LEG_004",
        strategyId: "STRATEGY_996751",
        strategyName: "NIFTY_NEW",
        symbol: "NIFTY",
        expiry: 0,
        priceType: "BIDASK",
        depthIndex: 1,
        orderType: "LIMIT",
        action: "SELL",
        optionType: "PE",
        lots: 1,
        strike: "ATM",
        target: "POINTS",
        targetValue: 1.0,
        stoploss: "POINTS",
        stoplossValue: 1.0,
        startTime: "",
        waitAndTrade: 0.0,
        waitAndTradeLogic: "NONE",
        dynamicHedge: true,
        onSquareOffAction: "NONE",
        onTargetActionConfig: {
          actionType: "NONE",
          actionCount: 1,
          orderAtBroker: false,
          slOrderAdjust: {
            minPoints: 0.0,
            maxPercentage: 0.0,
          },
        },
        onStoplossActionConfig: {
          actionType: "NONE",
          actionCount: 1,
          orderAtBroker: false,
          slOrderAdjust: {
            minPoints: 0.0,
            maxPercentage: 0.0,
          },
        },
        onSquareOffActionConfig: {
          actionType: "NONE",
          actionCount: 1,
          orderAtBroker: false,
          slOrderAdjust: {
            minPoints: 0.0,
            maxPercentage: 0.0,
          },
        },
        premiumBasedStrike: true,
        premiumBasedStrikeConfig: {
          strikeType: "NearestPremium",
          maxDepth: 25,
          searchSide: "OTM",
          value: 20.0,
          condition: "Greaterthanequal",
          between: 0.0,
          and_value: 0.0,
        },
        hedgeSelectedStrike: null,
        selectedStrike: null,
        reEnterCount: 0,
        reEnterLogic: "NONE",
        initialLegPrice: 0,
      },
    },
    exitSettings: {
      exitOrderType: "LIMIT",
      exitSellFirst: false,
      holdBuyTime: 0.0,
      waitBtwnRetry: 0.0,
      maxWaitTime: 0.0,
    },
    baseConfig: {
      strategyId: "STRATEGY_996751",
      strategyName: "NIFTY_NEW",
      lots: 1,
      underlying: "Spot",
      buyTradesFirst: false,
      executionMode: "Live Mode",
      isSelectedForTrading: true,
      tradingState: "START",
      strategyState: "NONE",
    },
    atBrokerSettings: {
      legSlAtBroker: false,
      legTpAtBroker: false,
      legReEntryAtBroker: false,
      legWnTAtBroker: false,
      slOrderTriggerAdjust: {
        minPoints: 0.0,
        maxPercentage: 0.0,
      },
    },
    dynamicHedgeSettings: {
      hedgeType: "fixed Distance",
      minHedgeDistance: 0,
      maxHedgeDistance: 0,
      minPremium: 0.0,
      maxPremium: 0.0,
      strikeSteps: {
        NIFTY: 50,
      },
      strike500: false,
      strikeDistance: 1,
    },
    stoplossSettings: {
      stoplossType: "CombinedProfit",
      stoplossValue: 0.0,
      stoplossWait: 0.0,
      sqrOffOnlyLossLegs: false,
      sqrOffOnlyProfitLegs: false,
    },
  },
];

export {
  startTradingState,
  pauseTradingState,
  resumeTradingState,
  stopTradingState,
  SampleData,
};
